In [1]:
import pandas as pd

Importing data tables

In [3]:
summary_df = pd.read_csv("Revised_merged_summary.csv")
summary_df.columns

/tmp/ipykernel_61984/3502892333.py:1: DtypeWarning: Columns (3,26) have mixed types. Specify dtype option on import or set low_memory=False.
  summary_df = pd.read_csv("Revised_merged_summary.csv")

Index(['id', 'company_name', 'establishment_name', 'ein', 'street_address',
       'city', 'state', 'zip_code', 'naics_code', 'industry_description',
       'annual_average_employees', 'total_hours_worked',
       'no_injuries_illnesses', 'total_deaths', 'total_dafw_cases',
       'total_djtr_cases', 'total_other_cases', 'total_dafw_days',
       'total_djtr_days', 'total_injuries', 'total_poisonings',
       'total_respiratory_conditions', 'total_skin_disorders',
       'total_hearing_loss', 'total_other_illnesses', 'establishment_id',
       'establishment_type', 'size', 'year_filing_for', 'created_timestamp',
       'change_reason'],
      dtype='object')

2019 Non_Construction_Site_analysis

In [4]:
df_2019 = pd.read_csv("3-VPP Annual Rates 2019 - Non-Construction Sites.csv")
df_2019.head()

,site_name,City,State,Region,NAICs,Union Site? Y or N,PSM Site? Y or N,2019 AVG. # of Site Employees,2019 AVG # of Applicable Contractor Employees,2019 Total # of Applicable Contractor Companies,...,TCIR ABOVE or Below?,2019 Annual DART Site Rate,2019 Annual Applicable Contractor DART Rate,New 3 Year (17-19) DART Site Rate,Previous 3 Year (16-18) DART Site Rate,2018 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,Honeywell International - Pottsv (28),Pottsville,PA,3.0,326113.0,N,N,133,0,0,...,Below,0.0,NaN,0.22,0.20,1.9,0.000000,2.603304,2.603304,Below
1,NB Coatings,Lansing,IL,5.0,325510.0,N,Y,368,18,2,...,Below,0.9,0,1.20,NaN,1.3,3.193308,4.612556,1.419248,Below
2,Akzo Nobel Coating (3),Reading,PA,3.0,325510.0,N,N,123,0,0,...,Below,0.8,NaN,1.14,0.50,1.0,0.995264,1.244080,0.248816,Below
3,"Potlatch Land & Lumber, LLC",Saint Maries,ID,10.0,321113.0,N,N,401,6,1,...,Below,0.3,116.0,1.20,1.8,1.8,0.983350,7.080120,6.096770,Below
4,Clearwater Paper Consumer Produc,Lewiston,ID,10.0,322121.0,Y,N,427,12,2,...,Below,0.7,0.0,0.50,0.5,1.2,3.000731,5.295408,2.294677,Below

In [10]:
df_2019['site_name'] = df_2019['site_name'] .str.strip(
).str.lower()
df_2019['City'] = df_2019['City'].str.strip().str.lower()
df_2019['State'] = df_2019['State'].str.strip().str.lower()

In [9]:
summary_df['establishment_name'] = summary_df['establishment_name'] .str.strip(
).str.lower()
summary_df['city'] = summary_df['city'].str.strip().str.lower()
summary_df['state'] = summary_df['state'].str.strip().str.lower()

In [11]:
vpp_2019_find = pd.merge(summary_df, df_2019,
                         left_on=['establishment_name', 'city','state'],
                         right_on=['site_name', 'City','State'])
vpp_2019_find.head(5)

,id,company_name,establishment_name,ein,street_address,city,state,zip_code,naics_code,industry_description,...,TCIR ABOVE or Below?,2019 Annual DART Site Rate,2019 Annual Applicable Contractor DART Rate,New 3 Year (17-19) DART Site Rate,Previous 3 Year (16-18) DART Site Rate,2018 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,1091484.0,Norbord,norbord mississippi,640834496.0,1194 Hwy 145,guntown,ms,38849.0,321113.0,"Boards, wood, made from logs or bolts",...,Below,0.7,0.0,0.5,NaN,1.1,0.952539,1.496847,0.544308,Below
1,148216.0,Norbord,norbord mississippi,NaN,1194 Hwy 145,guntown,ms,38849.0,321113.0,"Boards, wood, made from logs or bolts",...,Below,0.7,0.0,0.5,NaN,1.1,0.952539,1.496847,0.544308,Below
2,454353.0,Norbord,norbord mississippi,NaN,1194 Hwy 145,guntown,ms,38849.0,321113.0,"Boards, wood, made from logs or bolts",...,Below,0.7,0.0,0.5,NaN,1.1,0.952539,1.496847,0.544308,Below
3,792699.0,Norbord,norbord mississippi,640834496.0,1194 Hwy 145,guntown,ms,38849.0,321113.0,"Boards, wood, made from logs or bolts",...,Below,0.7,0.0,0.5,NaN,1.1,0.952539,1.496847,0.544308,Below
4,492394.0,Norbord,norbord mississippi,NaN,1194 Hwy 145,guntown,ms,38849.0,321113.0,"Boards, wood, made from logs or bolts",...,Below,0.7,0.0,0.5,NaN,1.1,0.952539,1.496847,0.544308,Below

In [12]:
vpp_2019_find.to_csv("vpp_2019_df.csv", index=False)

2019 Construction Sites Analysis

In [13]:
df_2019_cs = pd.read_csv("3-VPP Annual Rates 2019 - Construction Sites.csv")
df_2019_cs.head()

,site_name,City,State,Region,NAICs,Union Site? Y or N,PSM Site? Y or N,2019 AVG. # of Site Employees,2019 Estimated Total Hrs Worked,2019 Annual TCIR Site Rate,...,TCIR I&I Avoided,TCIR ABOVE or Below?,2019 Annual DART Site Rate,New 3 Year (17-19) DART Site Rate,Previous 3 Year (16-18) DART Site Rate,2018 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,LPR Construction Company*,Loveland,CO,8,238120,No,No,248,"415,670",0.0,...,8,Below,0.0,0.3,0.3,2.6,0,5,5.4,Below
1,Turner Construction Company,Cincinnati,OH,5,238990,NaN,NaN,NaN,NaN,NaN,...,0,Below,NaN,NaN,NaN,NaN,0,0,0.0,Below
2,Danis Building Construction Co*,Miamisburg,OH,5,236220,N,N,2760,5559305,0.9,...,50,Below,0.2,0.3,0.1,1.6,6,44,38.9,Below
3,"L.F. Driscoll Co., LLC - HUP Ren (98)",Philadelphia,PA,3,236220,Y,N,58,121754,0,...,2,Below,0,0,1,0.5,0,0,0.3,Below
4,TP Mechanical Contractors*,Cincinnati,OH,5,238220,N,N,442,946166,1.2,...,7,Below,0.9,0.7,1.4,NaN,4,0,-4.3,ABOVE

In [14]:
df_2019_cs['site_name'] = df_2019_cs['site_name'] .str.strip(
).str.lower()
df_2019_cs['City'] = df_2019_cs['City'].str.strip().str.lower()
df_2019_cs['State'] = df_2019_cs['State'].str.strip().str.lower()

In [16]:
vpp_2019_cs_find = pd.merge(summary_df, df_2019_cs,
                         left_on=['establishment_name', 'city', 'state'],
                         right_on=['site_name', 'City', 'State'])
vpp_2019_cs_find.head(5)

,id,company_name,establishment_name,ein,street_address,city,state,zip_code,naics_code,industry_description,...,TCIR I&I Avoided,TCIR ABOVE or Below?,2019 Annual DART Site Rate,New 3 Year (17-19) DART Site Rate,Previous 3 Year (16-18) DART Site Rate,2018 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,1097150.0,"Marker, Inc.","marker, inc.",344476858.0,2084 US 68 South,bellefontaine,oh,43311.0,236220.0,Commercial building construction,...,4,Below,1.2,1.0,1.4,NaN,5,0,-5.1,ABOVE
1,1439976.0,"Marker, Inc.","marker, inc.",344476858.0,2084 US 68 South,bellefontaine,oh,43311.0,236220.0,Commercial building construction,...,4,Below,1.2,1.0,1.4,NaN,5,0,-5.1,ABOVE
2,1804438.0,"Marker, Inc.","marker, inc.",344476858.0,2084 US 68 S,bellefontaine,oh,43311.0,236220.0,"Addition, alteration and renovation for-sale b...",...,4,Below,1.2,1.0,1.4,NaN,5,0,-5.1,ABOVE
3,1323533.0,"Chapel Electric Co., LLC","chapel electric co., llc",NaN,1985 Founders Drive,dayton,oh,45420.0,238210.0,Electrical Contractors and Other Wiring Instal...,...,1,Below,0.0,0.0,NaN,1.3,0,3,3.3,Below
4,176277.0,"Chapel Electric Co., LLC","chapel electric co., llc",NaN,1985 Founders Drive,dayton,oh,45420.0,238210.0,Electrical Contractors and Other Wiring Instal...,...,1,Below,0.0,0.0,NaN,1.3,0,3,3.3,Below

In [17]:
vpp_2019_cs_find.to_csv("vpp_2019_cs.csv", index=False)

2020 Construction Sites Analysis

In [22]:
vpp_2020_cs_df = pd.read_csv(
    "3-VPP Annual Rates 2020.xlsx - Construction Sites.csv")
vpp_2020_cs_df.head()

,site_name,City,State,Region,NAICs,Union Site? Y or N,PSM Site? Y or N,PSM Supplement Questions Rcv'd Y or N,Does Your Site Use Pressure Relief Vessels in their Processes? Y or N,2020 AVG. # of Site Employees,...,DART I&I Avoided,DART ABOVE or Below?,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,Torcon (224),Philadelphia,PA,3,NaN,NaN,NaN,N,N,50.0,...,0.177494,Below,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"H.A. Dorsten, Inc.*",Minster,Ohio,5,2362.0,N,N,NaN,NaN,65.0,...,2.448287,Below,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ECC Guam Office,Tamuning,GU,9,562910.0,N,N,NaN,NaN,63.0,...,0.186972,Below,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Walsh Group,Fort Lewis,WA,10,236220.0,N,N,NaN,N,35.0,...,0.340109,Below,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Covanta Field Services South Group*,Hernando,FL,4,811310.0,N,N,N,N,47.0,...,0.430518,Below,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
vpp_2020_cs_df['site_name'] = vpp_2020_cs_df['site_name'] .str.strip(
).str.lower()
vpp_2020_cs_df['City'] = vpp_2020_cs_df['City'].str.strip().str.lower()
vpp_2020_cs_df['State'] = vpp_2020_cs_df['State'].str.strip().str.lower()

Merging with Summary data

In [25]:
vpp_2020 = pd.merge(summary_df, vpp_2020_cs_df,
                    left_on=['establishment_name'],
                            right_on=['site_name'])
vpp_2020.head(5)

,id,company_name,establishment_name,ein,street_address,city,state,zip_code,naics_code,industry_description,...,DART I&I Avoided,DART ABOVE or Below?,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
0,1096223.0,"Morris Construction, Inc.",NaN,370840998.0,1406 South Eaton St.,robinson,il,62454.0,238220.0,Pipe fitting contractors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1096223.0,"Morris Construction, Inc.",NaN,370840998.0,1406 South Eaton St.,robinson,il,62454.0,238220.0,Pipe fitting contractors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1096223.0,"Morris Construction, Inc.",NaN,370840998.0,1406 South Eaton St.,robinson,il,62454.0,238220.0,Pipe fitting contractors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1096223.0,"Morris Construction, Inc.",NaN,370840998.0,1406 South Eaton St.,robinson,il,62454.0,238220.0,Pipe fitting contractors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1096223.0,"Morris Construction, Inc.",NaN,370840998.0,1406 South Eaton St.,robinson,il,62454.0,238220.0,Pipe fitting contractors,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
vpp_2020.to_csv("vpp_2020_CS(unfiltered).csv", index=False)

2020 Non_Construction Sites Analysis

In [27]:
vpp_2020_non_cs = pd.read_csv(
    "3-VPP Annual Rates 2020.xlsx - Non-Construction Sites.csv")
vpp_2020_non_cs.head()

,site_name,City,State,Region,NAICs,Union Site? Y or N,PSM Site? Y or N,2020 AVG. # of Site Employees,2020 AVG # of Applicable Contractor Employees,2020 Total # of Applicable Contractor Companies,...,TCIR ABOVE or Below?,2020 Annual DART Site Rate,2020 Annual Applicable Contractor DART Rate,New 3 Year (18-20) DART Site Rate,Previous 3 Year (17-19) DART Site Rate,2019 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,Wheelabrator Concord Co,Penacook,New Hampshire,1.0,562213.0,N,N,36,NaN,0,...,Below,0.0,NaN,2.484,3,NaN,0.0,0.0,0.0,Below
1,Covanta Energy of Southeastern Connecticut,Preston,Connecticut,1.0,562213.0,N,N,40,NaN,0,...,Below,0.0,NaN,0.716,1,NaN,0.0,0.0,0.0,Below
2,Raytheon Company Burlington,Burlington,Massachusetts,1.0,541330.0,Y,N,336,NaN,0,...,ABOVE,0.0,NaN,0,0,NaN,0.0,0.0,0.0,Below
3,Raytheon Company Waltham - Global Headquarters,Waltham,Massachusetts,1.0,551114.0,Y,N,350,NaN,0,...,ABOVE,0.0,NaN,0.166,3,NaN,0.0,0.0,0.0,Below
4,Raytheon Company Billerica,Billerica,Massachusetts,1.0,55111.0,Y,N,510,NaN,0,...,Below,0.0,NaN,0.126,2,NaN,0.0,0.0,0.0,Below

In [28]:
vpp_2020_non_cs['site_name'] = vpp_2020_non_cs['site_name'] .str.strip(
).str.lower()
vpp_2020_non_cs['City'] = vpp_2020_non_cs['City'].str.strip().str.lower()
vpp_2020_non_cs['State'] = vpp_2020_non_cs['State'].str.strip().str.lower()

Merging with Summary data

In [29]:
vpp_2020_non_cs = pd.merge(summary_df, vpp_2020_non_cs,
                    left_on=['establishment_name', 'city', 'state'],
                    right_on=['site_name', 'City', 'State'])
vpp_2020_non_cs.head(5)

,id,company_name,establishment_name,ein,street_address,city,state,zip_code,naics_code,industry_description,...,TCIR ABOVE or Below?,2020 Annual DART Site Rate,2020 Annual Applicable Contractor DART Rate,New 3 Year (18-20) DART Site Rate,Previous 3 Year (17-19) DART Site Rate,2019 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,1090938.0,J&J Snack Foods Corp,mia products,NaN,4 Rocky Glen Road,moosic,pa,18507.0,311520.0,Frozen desserts (except bakery) manufacturing,...,Below,1.8,0.0,1.2,NaN,4.3,4.008642,9.419215,5.410572,Below
1,1455.0,J&J Snack Foods Corp,mia products,NaN,4 Rocky Glen Road,moosic,pa,18507.0,311520.0,Frozen desserts (except bakery) manufacturing,...,Below,1.8,0.0,1.2,NaN,4.3,4.008642,9.419215,5.410572,Below
2,1434983.0,J&J Snack Foods Corp,mia products,NaN,4 Rocky Glen Road,moosic,pa,18507.0,311520.0,Frozen desserts (except bakery) manufacturing,...,Below,1.8,0.0,1.2,NaN,4.3,4.008642,9.419215,5.410572,Below
3,217017.0,J&J Snack Foods Corp,mia products,NaN,4 Rocky Glen Road,moosic,pa,18507.0,311520.0,Frozen desserts (except bakery) manufacturing,...,Below,1.8,0.0,1.2,NaN,4.3,4.008642,9.419215,5.410572,Below
4,791110.0,J&J Snack Foods Corp,mia products,NaN,4 Rocky Glen Road,moosic,pa,18507.0,311520.0,Frozen desserts (except bakery) manufacturing,...,Below,1.8,0.0,1.2,NaN,4.3,4.008642,9.419215,5.410572,Below

In [30]:
vpp_2020_non_cs.to_csv("vpp_2020_non_CS.csv", index=False)

2021 Construction Sites analysis

In [31]:
vpp_2021_CS = pd.read_csv("3-VPP Annual Rates 2021 - Construction SItes.csv")
vpp_2021_CS.head()

,site_name,City,State,Region,NAICs,Union Site? Y or N,PSM Site? Y or N,PSM Supplement Questions Rcv'd Y or N,Does Your Site Use Pressure Relief Vessels in their Processes? Y or N,2021 AVG. # of Site Employees,...,TCIR I&I Avoided,TCIR ABOVE or Below?,2021 Annual DART Site Rate,New 3 Year (19-21) DART Site Rate,Previous 3 year (18-20) DART Site Rate,2020 BLS Avg DART Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,Cianbro Corporation,Pittsfield,Maine,REGION 1,237990.0,N,N,NaN,NaN,2326.0,...,-18.996848,ABOVE,0.000,0.046,0.102,NaN,0.000000,0.0,0.000000,Below
1,"CFE, Inc.-Elmira*",Elmira,New York,REGION 2,238160.0,N,N,NaN,NaN,68.0,...,-8.999968,ABOVE,36.973,11.276,1.264,NaN,8.999968,0.0,-8.999968,ABOVE
2,"Charles F. Evans Company, Inc.*",Elmira,New York,REGION 2,238160.0,Y,N,NaN,NaN,42.0,...,0.000000,Below,0.000,1.275,1.357,NaN,0.000000,0.0,0.000000,Below
3,D.A. Collins Environmental*,Wilton,New York,REGION 2,562910.0,N,N,NaN,NaN,NaN,...,0.000000,Below,NaN,NaN,NaN,NaN,0.000000,0.0,0.000000,Below
4,EHS Excellence Consulting,Iselin,New Jersey,REGION 2,541690.0,N,N,NaN,NaN,6.0,...,0.000000,Below,0.000,0.000,0.000,NaN,0.000000,0.0,0.000000,Below

In [32]:
vpp_2021_CS['site_name'] = vpp_2021_CS['site_name'] .str.strip(
).str.lower()
vpp_2021_CS['City'] = vpp_2021_CS['City'].str.strip().str.lower()
vpp_2021_CS['State'] = vpp_2021_CS['State'].str.strip().str.lower()

In [35]:
vpp_2021_CS_df = pd.merge(summary_df, vpp_2021_CS,
                           left_on=['establishment_name', 'naics_code'],
                           right_on=['site_name', 'NAICs'])
vpp_2021_CS_df.head()

,id,company_name,establishment_name,ein,street_address,city,state,zip_code,naics_code,industry_description,...,TCIR I&I Avoided,TCIR ABOVE or Below?,2021 Annual DART Site Rate,New 3 Year (19-21) DART Site Rate,Previous 3 year (18-20) DART Site Rate,2020 BLS Avg DART Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,1097150.0,"Marker, Inc.","marker, inc.",344476858.0,2084 US 68 South,bellefontaine,oh,43311.0,236220.0,Commercial building construction,...,-1.000788,ABOVE,0.000,0.141,0.279,NaN,0.000000,0.0,0.000000,Below
1,1439976.0,"Marker, Inc.","marker, inc.",344476858.0,2084 US 68 South,bellefontaine,oh,43311.0,236220.0,Commercial building construction,...,-1.000788,ABOVE,0.000,0.141,0.279,NaN,0.000000,0.0,0.000000,Below
2,1804438.0,"Marker, Inc.","marker, inc.",344476858.0,2084 US 68 S,bellefontaine,oh,43311.0,236220.0,"Addition, alteration and renovation for-sale b...",...,-1.000788,ABOVE,0.000,0.141,0.279,NaN,0.000000,0.0,0.000000,Below
3,1210840.0,ECC,ecc,611075360.0,1304 Governors Court Suites 101 & 102,abingdon,md,21009.0,562910.0,Environmental remediation services,...,-1.000105,ABOVE,0.000,0.000,0.000,NaN,0.000000,0.0,0.000000,Below
4,1323533.0,"Chapel Electric Co., LLC","chapel electric co., llc",NaN,1985 Founders Drive,dayton,oh,45420.0,238210.0,Electrical Contractors and Other Wiring Instal...,...,-5.001268,ABOVE,0.783,0.749,0.717,NaN,1.998976,0.0,-1.998976,ABOVE

In [36]:
vpp_2021_CS_df.to_csv("vpp_2021_CS.csv", index=False)

2021 Non Construction Sites Analysis

In [37]:
vpp_2021_non_df = pd.read_csv(
    "3-VPP Annual Rates 2021 - Non-Construction Sites.csv")
vpp_2021_non_df.head()

,site_name,City,State,Region,NAICs,Union Site? Y or N,PSM Site? Y or N,2021 AVG. # of Site Employees,2021 AVG # of Applicable Contractor Employees,2021 Total # of Applicable Contractor Companies,...,TCIR ABOVE or Below?,2021 Annual DART Site Rate,2021 Annual Applicable Contractor DART Rate,New 3 Year (19-21) DART Site Rate,Previous 3 Year (18-20) DART Site Rate,2020 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,"Acushnet Co., Ball Plant II",North Dartmouth,Massachusetts,REGION 1,339920.0,N,N,376.0,NaN,3.0,...,ABOVE,3.266,NaN,3.176,2.001,NaN,9.999724,0.000000,-9.999724,ABOVE
1,Calpine - Westbrook Energy Center,Westbrook,Maine,REGION 1,221112.0,N,Y,21.0,NaN,0.0,...,Below,0.000,NaN,0.000,0.000,0.9,0.000000,0.183510,0.183510,Below
2,Dighton Power LLC,Dighton,Massachusetts,REGION 1,221112.0,N,N,16.0,NaN,0.0,...,Below,0.000,NaN,0.000,0.000,0.9,0.000000,0.144940,0.144940,Below
3,Dominion Millstone Power Station,Waterford,Connecticut,REGION 1,221113.0,N,N,884.0,NaN,0.0,...,Below,0.000,NaN,0.000,0.000,0.2,0.000000,1.773855,1.773855,Below
4,Huntsman LLC,Derry,New Hampshire,REGION 1,325211.0,N,N,11.0,NaN,0.0,...,Below,0.000,NaN,0.000,0.000,1.0,0.000000,0.083845,0.083845,Below

In [38]:
vpp_2021_non_df['site_name'] = vpp_2021_non_df['site_name'] .str.strip(
).str.lower()
vpp_2021_non_df['City'] = vpp_2021_non_df['City'].str.strip().str.lower()
vpp_2021_non_df['State'] = vpp_2021_non_df['State'].str.strip().str.lower()

Merging with summary data

In [41]:
vpp_2021_non_CS_df = pd.merge(summary_df, vpp_2021_non_df,
                          left_on=['establishment_name','naics_code'],
                          right_on=['site_name', 'NAICs'])
vpp_2021_non_CS_df.head()

,id,company_name,establishment_name,ein,street_address,city,state,zip_code,naics_code,industry_description,...,TCIR ABOVE or Below?,2021 Annual DART Site Rate,2021 Annual Applicable Contractor DART Rate,New 3 Year (19-21) DART Site Rate,Previous 3 Year (18-20) DART Site Rate,2020 BLS Avg DART Site Rate,DART I&I Experienced,DART I&I if BLS Avg,DART I&I Avoided,DART ABOVE or Below?
0,1095403.0,International Paper Company,international paper,NaN,660 South 83rd Ave.,tolleson,az,85353.0,322211.0,"Boxes, corrugated and solid fiber, made from ...",...,Below,0.641,NaN,0.233,0.0,1.6,0.999271,2.49428,1.495009,Below
1,1119331.0,International Paper,international paper,130872805.0,1111 AT&T Center Parkway,san antonio,tx,78219.0,322211.0,"Boxes, corrugated and solid fiber, made from ...",...,Below,0.641,NaN,0.233,0.0,1.6,0.999271,2.49428,1.495009,Below
2,1153455.0,International Paper,international paper,2141578.0,5032 S. Davy Crockett Pkwy,morristown,tn,37813.0,322211.0,"Boxes, corrugated and solid fiber, made from ...",...,Below,0.641,NaN,0.233,0.0,1.6,0.999271,2.49428,1.495009,Below
3,1215188.0,INTERNATIONAL PAPER,international paper,NaN,10 wilson Rd.,eighty four,pa,15330.0,322211.0,"Boxes, corrugated and solid fiber, made from ...",...,Below,0.641,NaN,0.233,0.0,1.6,0.999271,2.49428,1.495009,Below
4,1234189.0,International Paper,international paper,NaN,370 Benigno Blvd,bellmawr,nj,8031.0,322211.0,Corrugated paper made from purchased paper or...,...,Below,0.641,NaN,0.233,0.0,1.6,0.999271,2.49428,1.495009,Below

In [42]:
vpp_2021_non_CS_df.to_csv("vpp_2021_non_cs.csv", index=False)